name: Test Yahoo Query Data Retrieval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify a stable Python version

    - name: Create Data directory
      run: |
        mkdir -p Data
        echo "Created Data directory"
        ls -la

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxml2-dev \
          libxslt-dev \
          python3-dev \
          build-essential \
          gcc \
          pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-cache-dir lxml  # Install lxml separately first
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v tests/test_yq_data.py

    - name: Debug directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Data directory contents:"
        ls -la Data/
        echo "Finding all CSV files:"
        find . -name "*.csv"

    # Keep creating the artifact for download
    - name: Upload Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v3.1.2
      with:
        name: xle-data
        path: Data/XLE_data_*.csv
        retention-days: 5

    # New step to commit and push the CSV file to the repository
    - name: Commit and push CSV files
      run: |
        # Configure git
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Add CSV files to git
        git add Data/XLE_data_*.csv
        
        # Create a commit message with current date
        git commit -m "Update XLE data $(date +'%Y-%m-%d')" || echo "No changes to commit"
        
        # Push changes
        git push 